# Generated by Django 5.0.6 on 2024-07-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("savings", "Savings"),
                    ("checking", "Checking"),
                    ("loan", "Loan"),
                    ("store", "Store"),
                ],
                max_length=10,
            ),
        ),
    ]
