# Generated by Django 5.0.6 on 2024-07-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_bankaccount_account_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
