# Generated by Django 5.0.6 on 2024-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_invoice_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
