# Generated by Django 5.0.6 on 2024-07-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_invoice_total_amount_alter_invoiceitem_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="remaining_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
