# Generated by Django 5.0.6 on 2024-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_invoice_remaining_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
