# Generated by Django 5.0.6 on 2024-07-13 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_transference"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_change",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("date_changed", models.DateTimeField(auto_now_add=True)),
                (
                    "mother_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_history",
                        to="app.bankaccount",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
