# Generated by Django 5.0.6 on 2024-07-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_remove_product_user_alter_product_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producthistory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_history",
                to="app.product",
            ),
        ),
    ]
